services:
  postgres_yoga:
    container_name: postgres_yoga
    image: postgres:17.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5670:5670"
    expose:
      - 5670
    command: -p 5670

  backend_yoga:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres_yoga
    env_file:
      - .env

  frontend_yoga:
    image:  yaga-frontend:amd64
    ports:
      - "3000:3000"
    depends_on:
      - backend_yoga
    env_file:
      - .env

  nginx_yoga:
    container_name: nginx_yoga
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./keys:/etc/nginx/ssl:ro
    depends_on:
      - frontend_yoga
      - backend_yoga